[profile.default]
src = "src"
out = "out"
via_ir = true

remappings = [
  'forge-std/=lib/forge-std/src/',
  '@openzeppelin-contracts-5.0.2/=lib/openzeppelin-contracts/contracts/'
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
